# EarthquakeEvents.cmake
# Usage:
#   include(path/to/WindEvents.cmake)
#   simcenter_add_wind_events(<target>)


set(EVENTS_MODULE_DIR "${CMAKE_CURRENT_LIST_DIR}")

function(simcenter_add_wind_events target)
  set(dir "${EVENTS_MODULE_DIR}/EVENTS")

  target_include_directories(${target} PRIVATE
    "${EVENTS_MODULE_DIR}"
    "${dir}"
    "${dir}/StochasticWindModel/include"
    "${dir}/Inflow"
    "${dir}/BasicCFD"
    "${dir}/ExpertCFD"
    "${dir}/ExpertCFD/UI"
    "${dir}/ExpertCFD/Analysis"
    "${dir}/ExpertCFD/CFDanalysis"
    "${dir}/ExpertCFD/SimCenter_widgets"
    "${dir}/DigitalWindTunnel"
    "${dir}/IsolatedBuildingCFD"
    "${dir}/AdvancedCFDWithBRAILS"
  )  

  set (SOURCES
    "${dir}/BasicCFD/BasicCFDv2.cpp"
    "${dir}/DigitalWindTunnel/DigitalWindTunnel.cpp"
    "${dir}/AdvancedCFDWithBRAILS/AdvancedCFDWithBRAILS.cpp"    
    "${dir}/IsolatedBuildingCFD/IsolatedBuildingCFD.cpp"
    "${dir}/IsolatedBuildingCFD/SimCenterVTKRenderingWidget.cpp"
    "${dir}/IsolatedBuildingCFD/GeometricInputWidget.cpp"
    "${dir}/IsolatedBuildingCFD/SnappyHexMeshWidget.cpp"
    "${dir}/IsolatedBuildingCFD/BoundaryConditionsWidget.cpp"
    "${dir}/IsolatedBuildingCFD/TurbulenceModelingWidget.cpp"
    "${dir}/IsolatedBuildingCFD/NumericalSetupWidget.cpp"
    "${dir}/IsolatedBuildingCFD/WindCharacteristicsWidget.cpp"
    "${dir}/IsolatedBuildingCFD/ResultMonitoringWidget.cpp"
    "${dir}/IsolatedBuildingCFD/ResultDisplayWidget.cpp"
    "${dir}/EmptyDomainCFD/EmptyDomainCFD.cpp"
    "${dir}/EmptyDomainCFD/EmptyVTKRendering.cpp"
    "${dir}/EmptyDomainCFD/EmptyGeometricInput.cpp"
    "${dir}/EmptyDomainCFD/EmptySnappyHexMesh.cpp"
    "${dir}/EmptyDomainCFD/EmptyBoundaryConditions.cpp"
    "${dir}/EmptyDomainCFD/EmptyTurbulenceModeling.cpp"
    "${dir}/EmptyDomainCFD/EmptyNumericalSetup.cpp"
    "${dir}/EmptyDomainCFD/EmptyWindCharacteristics.cpp"
    "${dir}/EmptyDomainCFD/EmptyResultMonitoring.cpp"
    "${dir}/EmptyDomainCFD/EmptyResultDisplay.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingCFD.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingVTKRendering.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingGeometricInput.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingSnappyHexMesh.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingBoundaryConditions.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingTurbulenceModeling.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingNumericalSetup.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingWindCharacteristics.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingResultMonitoring.cpp"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingResultDisplay.cpp"
    "${dir}/ExpertCFD/CFDanalysis/CFDanalysisType.cpp"
    "${dir}/ExpertCFD/CFDanalysis/CFDcaseInstance.cpp"
    "${dir}/ExpertCFD/CFDExpertWidget.cpp"
    "${dir}/ExpertCFD/UI/CWE3DView.cpp"
    "${dir}/ExpertCFD/UI/Edged3DBox.cpp"
    "${dir}/ExpertCFD/UI/GeometryHelper.cpp"
    "${dir}/ExpertCFD/UI/CFDTemplateWidget.cpp"
    "${dir}/ExpertCFD/UI/Graphics3DAxes.cpp"
    "${dir}/ExpertCFD/UI/PatchesSelector.cpp"
    "${dir}/ExpertCFD/UI/RemoteCaseSelector.cpp"
    "${dir}/ExpertCFD/UI/SubdomainsModel.cpp"
    "${dir}/ExpertCFD/cfd_globals.cpp"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_parameters.cpp"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_state_label.cpp"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_groupswidget.cpp"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_parampanel.cpp"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_stagestatustab.cpp"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_tabwidget.cpp"
    "${dir}/ExpertCFD/OpenFoamHelper/openfoamhelper.cpp"
    "${dir}/Inflow/inflowparameterwidget.cpp"
    "${dir}/WindEventSelection.cpp"
    "${dir}/DEDM_HRP.cpp"
    "${dir}/BasicCFD/BasicCFD.cpp"
    "${dir}/BasicCFD/MeshParametersCWE.cpp"
    "${dir}/BasicCFD/SimulationParametersCWE.cpp"
    "${dir}/LowRiseTPU.cpp"
    "${dir}/HighRiseTPU.cpp"    
    "${dir}/WindTunnelExperiment.cpp"
    "${dir}/ExperimentalWindForces.cpp"
    "${dir}/ExperimentalWindPressures.cpp"
    "${dir}/TapsInputDelegate.cpp"
    "${dir}/WindForceSpectrum.cpp"
    "${dir}/StochasticWindModel/src/WittigSinha.cpp"
    "${dir}/StochasticWindModel/src/StochasticWindInput.cpp"
    "${dir}/ExpertCFD/Analysis/filemetadata.cpp"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrbooldatawidget.cpp"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrchoicedatawidget.cpp"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrfiledatawidget.cpp"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrmasterdatawidget.cpp"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrstddatawidget.cpp"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrtextdatawidget.cpp"
    "${dir}/ExpertCFD/Analysis/remotejobdata.cpp"
    "${dir}/initialmodalinfo.cpp"
    "${dir}/usermodeshapes.cpp"
  )

  set (HEADERS
    "${dir}/BasicCFD/BasicCFDv2.h"
    "${dir}/DigitalWindTunnel/DigitalWindTunnel.h"
    "${dir}/AdvancedCFDWithBRAILS/AdvancedCFDWithBRAILS.h"        
    "${dir}/IsolatedBuildingCFD/IsolatedBuildingCFD.h"
    "${dir}/IsolatedBuildingCFD/SimCenterVTKRenderingWidget.h"
    "${dir}/IsolatedBuildingCFD/GeometricInputWidget.h"
    "${dir}/IsolatedBuildingCFD/SnappyHexMeshWidget.h"
    "${dir}/IsolatedBuildingCFD/BoundaryConditionsWidget.h"
    "${dir}/IsolatedBuildingCFD/TurbulenceModelingWidget.h"
    "${dir}/IsolatedBuildingCFD/NumericalSetupWidget.h"
    "${dir}/IsolatedBuildingCFD/WindCharacteristicsWidget.h"
    "${dir}/IsolatedBuildingCFD/ResultMonitoringWidget.h"
    "${dir}/IsolatedBuildingCFD/ResultDisplayWidget.h"
    "${dir}/EmptyDomainCFD/EmptyDomainCFD.h"
    "${dir}/EmptyDomainCFD/EmptyVTKRendering.h"
    "${dir}/EmptyDomainCFD/EmptyGeometricInput.h"
    "${dir}/EmptyDomainCFD/EmptySnappyHexMesh.h"
    "${dir}/EmptyDomainCFD/EmptyBoundaryConditions.h"
    "${dir}/EmptyDomainCFD/EmptyTurbulenceModeling.h"
    "${dir}/EmptyDomainCFD/EmptyNumericalSetup.h"
    "${dir}/EmptyDomainCFD/EmptyWindCharacteristics.h"
    "${dir}/EmptyDomainCFD/EmptyResultMonitoring.h"
    "${dir}/EmptyDomainCFD/EmptyResultDisplay.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingCFD.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingVTKRendering.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingGeometricInput.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingSnappyHexMesh.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingBoundaryConditions.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingTurbulenceModeling.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingNumericalSetup.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingWindCharacteristics.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingResultMonitoring.h"
    "${dir}/SurroundedBuildingCFD/SurroundedBuildingResultDisplay.h"
    "${dir}/ExpertCFD/CFDanalysis/CFDanalysisType.h"
    "${dir}/ExpertCFD/CFDanalysis/CFDcaseInstance.h"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrstates.h"
    "${dir}/ExpertCFD/UI/CFDTemplateWidget.h"
    "${dir}/ExpertCFD/CFDExpertWidget.h"
    "${dir}/ExpertCFD/UI/CWE3DView.h"
    "${dir}/ExpertCFD/UI/Edged3DBox.h"
    "${dir}/ExpertCFD/UI/GeometryHelper.h"
    "${dir}/ExpertCFD/UI/Graphics3DAxes.h"
    "${dir}/ExpertCFD/UI/PatchesSelector.h"
    "${dir}/ExpertCFD/UI/RemoteCaseSelector.h"
    "${dir}/ExpertCFD/UI/SubdomainsModel.h"
    "${dir}/ExpertCFD/cfd_globals.h"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_parameters.h"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_state_label.h"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_groupswidget.h"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_parampanel.h"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_stagestatustab.h"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_tabwidget.h"
    "${dir}/ExpertCFD/OpenFoamHelper/openfoamhelper.h"
    "${dir}/Inflow/inflowparameterwidget.h"
    "${dir}/WindEventSelection.h"
    "${dir}/WindTunnelExperiment.h"
    "${dir}/ExperimentalWindForces.h"
    "${dir}/ExperimentalWindPressures.h"
    "${dir}/TapsInputDelegate.h"
    "${dir}/WindForceSpectrum.h"
    "${dir}/DEDM_HRP.h"
    "${dir}/BasicCFD/BasicCFD.h"
    "${dir}/BasicCFD/MeshParametersCWE.h"
    "${dir}/BasicCFD/SimulationParametersCWE.h"
    "${dir}/LowRiseTPU.h"
    "${dir}/HighRiseTPU.h"    
    "${dir}/StochasticWindModel/include/WittigSinha.h"
    "${dir}/StochasticWindModel/include/StochasticWindInput.h"
    "${dir}/ExpertCFD/Analysis/filemetadata.h"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrbooldatawidget.h"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrchoicedatawidget.h"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrfiledatawidget.h"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrmasterdatawidget.h"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrstddatawidget.h"
    "${dir}/ExpertCFD/SimCenter_widgets/sctrtextdatawidget.h"
    "${dir}/ExpertCFD/Analysis/remotejobdata.h"
    "${dir}/initialmodalinfo.h"
    "${dir}/usermodeshapes.h"
  )

  set (FORMS
    "${dir}/BasicCFD/BasicCFDv2.ui"
    "${dir}/DigitalWindTunnel/DigitalWindTunnel.ui"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_parameters.ui"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_parampanel.ui"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_stagestatustab.ui"
    "${dir}/ExpertCFD/cwe_guiWidgets/cwe_tabwidget/cwe_tabwidget.ui"
    "${dir}/Inflow/inflowparameterwidget.ui"
    "${dir}/usermodeshapes.ui"
  )

  target_sources(${target} PRIVATE ${SOURCES} ${HEADERS} ${FORMS})
  
endfunction()
    





